version: '3.8'

services:
  web:
    build:
      context: .
      args:
        APP_PORT: ${DOCKER_APP_PORT}
    env_file:
      - .env
    ports:
        - ${DOCKER_APP_PORT}:9000
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0
    environment:
      - TZ=Asia/Yekaterinburg

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: "redis-server --save 20 1 --loglevel warning"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-db:
  redis-data: